# Generated by Django 4.2.11 on 2024-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='User', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='none', upload_to='blog'),
            preserve_default=False,
        ),
    ]
